title = "EnWaJo config file"
description = ""

[model]
# solver options (if installed): "gurobi", "cplex", "glpk", "ipopt"
solver = "cbc"
# temporal resolution can be set with 1,2,3 (every x timestep is used)
t_resolution = 2
# start timestep
t_start = 0
# end timestep
t_end = 168

[constraints]
# binary constraints for minimal load of of units
pmin = false
